title: "Mohamed Alsaleh"
description: "Transportation Engineer | M.S. Graduate, LSU"
url: "https://mohamed-alsaleh.github.io"

timezone: America/Chicago

author:
  name: "Mohamed Alsaleh"
  email: "malsal7@lsu.edu"
  linkedin: "https://www.linkedin.com/in/mohamed-alsaleh"

source: .
destination: ./_site
includes: ./_includes

collections:
  projects:
    output: true
